<!DOCTYPE HTML>
<html lang="zh-cn" class="sidebar-visible no-js light">
    <head>
        <!-- Book generated using mdBook -->
        <meta charset="UTF-8">
        <title>64. 虚拟机是如何捕获异常的？ - CPython3.8 源码探秘</title>
        <!-- Custom HTML head -->
        <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="theme-color" content="#ffffff" />

        <link rel="icon" href="favicon.svg">
        <link rel="shortcut icon" href="favicon.png">
        <link rel="stylesheet" href="css/variables.css">
        <link rel="stylesheet" href="css/general.css">
        <link rel="stylesheet" href="css/chrome.css">
        <link rel="stylesheet" href="css/print.css" media="print">
        <!-- Fonts -->
        <link rel="stylesheet" href="FontAwesome/css/font-awesome.css">
        <link rel="stylesheet" href="fonts/fonts.css">
        <!-- Highlight.js Stylesheets -->
        <link rel="stylesheet" href="highlight.css">
        <link rel="stylesheet" href="tomorrow-night.css">
        <link rel="stylesheet" href="ayu-highlight.css">

        <!-- Custom theme stylesheets -->
        <link rel="stylesheet" href="theme/custom.css">
        <!-- MathJax -->
        <script async type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
    </head>
    <body>
        <!-- Provide site root to javascript -->
        <script type="text/javascript">
            var path_to_root = "";
            var default_theme = window.matchMedia("(prefers-color-scheme: dark)").matches ? "navy" : "light";
        </script>

        <!-- Work around some values being stored in localStorage wrapped in quotes -->
        <script type="text/javascript">
            try {
                var theme = localStorage.getItem('mdbook-theme');
                var sidebar = localStorage.getItem('mdbook-sidebar');

                if (theme.startsWith('"') && theme.endsWith('"')) {
                    localStorage.setItem('mdbook-theme', theme.slice(1, theme.length - 1));
                }

                if (sidebar.startsWith('"') && sidebar.endsWith('"')) {
                    localStorage.setItem('mdbook-sidebar', sidebar.slice(1, sidebar.length - 1));
                }
            } catch (e) { }
        </script>

        <!-- Set the theme before any content is loaded, prevents flash -->
        <script type="text/javascript">
            var theme;
            try { theme = localStorage.getItem('mdbook-theme'); } catch(e) { }
            if (theme === null || theme === undefined) { theme = default_theme; }
            var html = document.querySelector('html');
            html.classList.remove('no-js')
            html.classList.remove('light')
            html.classList.add(theme);
            html.classList.add('js');
        </script>

        <!-- Hide / unhide sidebar before it is displayed -->
        <script type="text/javascript">
            var html = document.querySelector('html');
            var sidebar = 'hidden';
            if (document.body.clientWidth >= 1080) {
                try { sidebar = localStorage.getItem('mdbook-sidebar'); } catch(e) { }
                sidebar = sidebar || 'visible';
            }
            html.classList.remove('sidebar-visible');
            html.classList.add("sidebar-" + sidebar);
        </script>

        <nav id="sidebar" class="sidebar" aria-label="Table of contents">
            <div class="sidebar-scrollbox">
                <ol class="chapter"><li class="chapter-item expanded "><a href="0.序言.html">0. 序言</a></li><li class="chapter-item expanded "><a href="1.CPython源码长什么样子？.html">1. CPython 源码长什么样子？</a></li><li class="chapter-item expanded "><a href="2.变量和对象，它们之间有什么区别和联系呢？.html">2. 变量和对象，它们之间有什么区别和联系呢？</a></li><li class="chapter-item expanded "><a href="3.Python对象有哪几种，我们可以从哪些角度进行分类呢？.html">3. Python 对象有哪几种，我们可以从哪些角度进行分类呢？</a></li><li class="chapter-item expanded "><a href="4.万丈高楼平地起，一切从PyObject开始.html">4. 万丈高楼平地起，一切从 PyObject 开始</a></li><li class="chapter-item expanded "><a href="5.详解PyTypeObject，Python类型对象的载体.html">5. 详解 PyTypeObject，Python 类型对象的载体</a></li><li class="chapter-item expanded "><a href="6.通过type和object之间的关联，进一步分析类型对象.html">6. 通过 type 和 object 之间的关联，进一步分析类型对象</a></li><li class="chapter-item expanded "><a href="7.当创建一个Python对象时，背后都经历了哪些过程？.html">7. 当创建一个 Python 对象时，背后都经历了哪些过程？</a></li><li class="chapter-item expanded "><a href="8.当调用一个Python对象时，背后都经历了哪些过程？.html">8. 当调用一个 Python 对象时，背后都经历了哪些过程？</a></li><li class="chapter-item expanded "><a href="9.再探泛型API，感受Python对象的设计哲学.html">9. 再探泛型 API，感受 Python 对象的设计哲学</a></li><li class="chapter-item expanded "><a href="10.Python对象的行为是怎么区分的？.html">10. Python 对象的行为是怎么区分的？</a></li><li class="chapter-item expanded "><a href="11.一个Python对象会在何时被销毁？.html">11. 一个 Python 对象会在何时被销毁？</a></li><li class="chapter-item expanded "><a href="12.深度解密Python的浮点数是怎么实现的？.html">12. 深度解密 Python 的浮点数是怎么实现的？</a></li><li class="chapter-item expanded "><a href="13.对象被销毁之后所占的内存一定会释放吗？解密浮点数的缓存池机制.html">13. 对象被销毁之后所占的内存一定会释放吗？解密浮点数的缓存池机制</a></li><li class="chapter-item expanded "><a href="14.浮点数支持的操作是怎么实现的？.html">14. 浮点数支持的操作是怎么实现的？</a></li><li class="chapter-item expanded "><a href="15.解密Python的复数是怎么实现的？它有什么用途呢？.html">15. 解密 Python 的复数是怎么实现的？它有什么用途呢？</a></li><li class="chapter-item expanded "><a href="16.Python的整数是怎么设计的，为什么它不会溢出？.html">16. Python 的整数是怎么设计的，为什么它不会溢出？</a></li><li class="chapter-item expanded "><a href="17.解密Python的小整数对象池.html">17. 解密 Python 的小整数对象池</a></li><li class="chapter-item expanded "><a href="18.两个Python整数之间是如何进行大小比较的？过程并不像我们想的那样简单.html">18. 两个 Python 整数之间是如何进行大小比较的？过程并不像我们想的那样简单</a></li><li class="chapter-item expanded "><a href="19.探究Python整数的加减法，感受大整数的运算哲学与魅力.html">19. 探究 Python 整数的加减法，感受大整数的运算哲学与魅力</a></li><li class="chapter-item expanded "><a href="20.Python的布尔值是怎么实现的，你对它的了解有多深呢？.html">20. Python 的布尔值是怎么实现的，你对它的了解有多深呢？</a></li><li class="chapter-item expanded "><a href="21.Python的None是怎么实现的？.html">21. Python 的 None 是怎么实现的？</a></li><li class="chapter-item expanded "><a href="22.深度解密Python切片的实现原理.html">22.深度解密 Python 切片的实现原理</a></li><li class="chapter-item expanded "><a href="23.bytes对象（字节串）是怎么实现的？解密它的内部原理.html">23. bytes 对象（字节串）是怎么实现的？解密它的内部原理</a></li><li class="chapter-item expanded "><a href="24.bytes对象都支持哪些操作，它们是怎么实现的？.html">24. bytes 对象都支持哪些操作，它们是怎么实现的？</a></li><li class="chapter-item expanded "><a href="25.通过bytes对象的合并，探究缓冲区的奥秘.html">25. 通过 bytes 对象的合并，探究缓冲区的奥秘</a></li><li class="chapter-item expanded "><a href="26.解密bytes对象的缓存池.html">26. 解密 bytes 对象的缓存池</a></li><li class="chapter-item expanded "><a href="27.详解bytearray对象的底层实现.html">27. 详解 bytearray 对象的底层实现</a></li><li class="chapter-item expanded "><a href="28.字符集和字符编码.html">28. 字符集和字符编码</a></li><li class="chapter-item expanded "><a href="29.Python是怎么存储字符串的？.html">29. Python 是怎么存储字符串的？</a></li><li class="chapter-item expanded "><a href="30.解密字符串的底层结构，它是怎么实现的？.html">30. 解密字符串的底层结构，它是怎么实现的？</a></li><li class="chapter-item expanded "><a href="31.字符串的intern机制是怎么一回事？.html">31. 字符串的 intern 机制是怎么一回事？</a></li><li class="chapter-item expanded "><a href="32.聊一聊字符串常见操作的源码实现.html">32. 聊一聊字符串常见操作的源码实现</a></li><li class="chapter-item expanded "><a href="33.列表是怎么实现的？解密列表的数据结构.html">33. 列表是怎么实现的？解密列表的数据结构</a></li><li class="chapter-item expanded "><a href="34.列表是怎么扩容的？.html">34. 列表是怎么扩容的？</a></li><li class="chapter-item expanded "><a href="35.解密列表的创建与销毁，以及缓存池长什么样子？.html">35. 解密列表的创建与销毁，以及缓存池长什么样子？</a></li><li class="chapter-item expanded "><a href="36.列表作为序列型对象都支持哪些操作，它们在底层是怎么实现的？.html">36. 列表作为序列型对象都支持哪些操作，它们在底层是怎么实现的？</a></li><li class="chapter-item expanded "><a href="37.列表都有哪些自定义方法，它们是怎么实现的？.html">37. 列表都有哪些自定义方法，它们是怎么实现的？</a></li><li class="chapter-item expanded "><a href="38.解密元组的实现原理.html">38. 解密元组的实现原理</a></li><li class="chapter-item expanded "><a href="39.聊一聊喜闻乐见的哈希表.html">39. 聊一聊喜闻乐见的哈希表</a></li><li class="chapter-item expanded "><a href="40.字典是怎么实现的，它的底层结构长什么样子？.html">40. 字典是怎么实现的，它的底层结构长什么样子？</a></li><li class="chapter-item expanded "><a href="41.什么是可哈希对象，它的哈希值是怎么计算的？.html">41. 什么是可哈希对象，它的哈希值是怎么计算的？</a></li><li class="chapter-item expanded "><a href="42.字典的key是怎么映射成索引的，索引冲突了又该怎么办？.html">42. 字典的 key 是怎么映射成索引的，索引冲突了又该怎么办？</a></li><li class="chapter-item expanded "><a href="43.哈希表是怎么删除元素的，能直接删除吗？.html">43. 哈希表是怎么删除元素的，能直接删除吗？</a></li><li class="chapter-item expanded "><a href="44.字典是怎么创建的，支持的操作又是如何实现的？.html">44. 字典是怎么创建的，支持的操作又是如何实现的？</a></li><li class="chapter-item expanded "><a href="45.字典的自定义方法是怎么实现的？.html">45. 字典的自定义方法是怎么实现的？</a></li><li class="chapter-item expanded "><a href="46.字典是怎么扩容的？它会经历哪些过程？.html">46. 字典是怎么扩容的？它会经历哪些过程？</a></li><li class="chapter-item expanded "><a href="47.身虽死，道未消，解密字典的缓存池.html">47. 身虽死，道未消，解密字典的缓存池</a></li><li class="chapter-item expanded "><a href="48.解密集合的实现原理.html">48. 解密集合的实现原理</a></li><li class="chapter-item expanded "><a href="49.集合支持的操作有哪些，它们是怎么实现的？.html">49. 集合支持的操作有哪些，它们是怎么实现的？</a></li><li class="chapter-item expanded "><a href="50.迭代器是怎么实现的？.html">50. 迭代器是怎么实现的？</a></li><li class="chapter-item expanded "><a href="51.Python源文件编译之后会得到什么，它的结构是怎样的？和字节码又有什么联系？.html">51. Python 源文件编译之后会得到什么，它的结构是怎样的？和字节码又有什么联系？</a></li><li class="chapter-item expanded "><a href="52.PyCodeObject拾遗.html">52. PyCodeObject 拾遗</a></li><li class="chapter-item expanded "><a href="53.一文让你搞懂pyc文件.html">53. 一文让你搞懂 pyc 文件</a></li><li class="chapter-item expanded "><a href="54.深度解密虚拟机的执行环境：栈帧对象.html">54. 深度解密虚拟机的执行环境：栈帧对象</a></li><li class="chapter-item expanded "><a href="55.名字空间：变量的容身之所.html">55. 名字空间：变量的容身之所</a></li><li class="chapter-item expanded "><a href="56.当查找一个变量时，虚拟机会进行哪些动作？.html">56. 当查找一个变量时，虚拟机会进行哪些动作？</a></li><li class="chapter-item expanded "><a href="57.虚拟机是怎么执行字节码的？背后都经历了哪些过程.html">57. 虚拟机是怎么执行字节码的？背后都经历了哪些过程</a></li><li class="chapter-item expanded "><a href="58.深入源码，进一步考察字节码的执行流程.html">58. 深入源码，进一步考察字节码的执行流程</a></li><li class="chapter-item expanded "><a href="59.局部变量是怎么实现静态查找的，它和local名字空间又有什么联系呢？.html">59. 局部变量是怎么实现静态查找的，它和 local 名字空间又有什么联系呢？</a></li><li class="chapter-item expanded "><a href="60.剖析字节码指令，以及Python赋值语句的原理.html">60. 剖析字节码指令，以及 Python 赋值语句的原理</a></li><li class="chapter-item expanded "><a href="61.流程控制语句if是怎么实现的？.html">61. 流程控制语句 if 是怎么实现的？</a></li><li class="chapter-item expanded "><a href="62.流程控制语句for、while是怎么实现的？.html">62. 流程控制语句 for、while 是怎么实现的？</a></li><li class="chapter-item expanded "><a href="63.异常是怎么实现的？虚拟机是如何将异常抛出去的？.html">63. 异常是怎么实现的？虚拟机是如何将异常抛出去的？</a></li><li class="chapter-item expanded "><a href="64.虚拟机是如何捕获异常的？.html" class="active">64. 虚拟机是如何捕获异常的？</a></li><li class="chapter-item expanded "><a href="65.函数在底层长什么样子？.html">65. 函数在底层长什么样子？</a></li><li class="chapter-item expanded "><a href="66.函数是怎么创建的，背后经历了哪些过程？.html">66. 函数是怎么创建的，背后经历了哪些过程？</a></li><li class="chapter-item expanded "><a href="67.函数在底层是如何调用的？.html">67. 函数在底层是如何调用的？</a></li><li class="chapter-item expanded "><a href="68.函数是如何解析位置参数的？.html">68. 函数是如何解析位置参数的？</a></li><li class="chapter-item expanded "><a href="69.函数是如何解析关键字参数的？.html">69. 函数是如何解析关键字参数的？</a></li><li class="chapter-item expanded "><a href="70.扩展位置参数和扩展关键字参数是如何解析的？.html">70. 扩展位置参数和扩展关键字参数是如何解析的？</a></li><li class="chapter-item expanded "><a href="71.闭包是怎么实现的？.html">71. 闭包是怎么实现的？</a></li><li class="chapter-item expanded "><a href="72.生成器是做什么的，为什么会有生成器？.html">72. 生成器是做什么的，为什么会有生成器？</a></li><li class="chapter-item expanded "><a href="73.源码解密生成器的实现原理.html">73. 源码解密生成器的实现原理</a></li><li class="chapter-item expanded "><a href="74.回顾Python的对象模型.html">74. 回顾 Python 的对象模型</a></li><li class="chapter-item expanded "><a href="75.class概念解析.html">75. class 概念解析</a></li><li class="chapter-item expanded "><a href="76.类型对象的初始化.html">76. 类型对象的初始化</a></li><li class="chapter-item expanded "><a href="77.自定义类对象的底层实现与metaclass.html">77. 自定义类对象的底层实现与 metaclass</a></li><li class="chapter-item expanded "><a href="78.彻底搞懂描述符.html">78. 彻底搞懂描述符</a></li><li class="chapter-item expanded "><a href="79.实例对象是如何创建的？.html">79. 实例对象是如何创建的？</a></li><li class="chapter-item expanded "><a href="80.实例对象的属性访问.html">80. 实例对象的属性访问</a></li><li class="chapter-item expanded "><a href="81.为什么实例在调用方法时会将自身传给self参数.html">81. 为什么实例在调用方法时会将自身传给 self 参数</a></li><li class="chapter-item expanded "><a href="82.模块是如何导入的？.html">82. 模块是如何导入的？</a></li><li class="chapter-item expanded "><a href="83.import机制的黑盒探测.html">83. import 机制的黑盒探测</a></li><li class="chapter-item expanded "><a href="84.import机制是怎么实现的？.html">84. import 机制是怎么实现的？</a></li><li class="chapter-item expanded "><a href="85.Python运行时环境的初始化，解释器在启动时都做了什么？.html">85. Python 运行时环境的初始化，解释器在启动时都做了什么？</a></li><li class="chapter-item expanded "><a href="86.激活Python虚拟机.html">86. 激活 Python 虚拟机</a></li><li class="chapter-item expanded "><a href="87.初识GIL、以及多个线程之间的调度机制.html">87. 初识 GIL、以及多个线程之间的调度机制</a></li><li class="chapter-item expanded "><a href="88.线程的创建、销毁、调度，以及GIL的实现原理.html">88. 线程的创建、销毁、调度，以及 GIL 的实现原理</a></li><li class="chapter-item expanded "><a href="89.解密map、filter、zip底层实现，对比列表解析式.html">89. 解密 map、filter、zip 底层实现，对比列表解析式</a></li><li class="chapter-item expanded "><a href="90.为什么要有协程，协程是如何实现的？.html">90. 为什么要有协程，协程是如何实现的？</a></li><li class="chapter-item expanded "><a href="91.什么是asyncio？如何基于单线程实现并发？事件循环又是怎么工作的？.html">91. 什么是 asyncio？如何基于单线程实现并发？事件循环又是怎么工作的？</a></li><li class="chapter-item expanded "><a href="92.协程、任务、future，以及事件循环.html">92. 协程、任务、future，以及事件循环</a></li><li class="chapter-item expanded "><a href="93.在asyncio中使用Socket.html">93. 在 asyncio 中使用 Socket</a></li><li class="chapter-item expanded "><a href="94.解密asyncio的Future和Task.html">94. 解密 asyncio 的 Future 和 Task</a></li></ol>
            </div>
            <div id="sidebar-resize-handle" class="sidebar-resize-handle"></div>
        </nav>

        <div id="page-wrapper" class="page-wrapper">

            <div class="page">
                <div id="menu-bar-hover-placeholder"></div>
                <div id="menu-bar" class="menu-bar sticky bordered">
                    <div class="left-buttons">
                        <button id="sidebar-toggle" class="icon-button" type="button" title="Toggle Table of Contents" aria-label="Toggle Table of Contents" aria-controls="sidebar">
                            <i class="fa fa-bars"></i>
                        </button>
                        <button id="theme-toggle" class="icon-button" type="button" title="Change theme" aria-label="Change theme" aria-haspopup="true" aria-expanded="false" aria-controls="theme-list">
                            <i class="fa fa-paint-brush"></i>
                        </button>
                        <ul id="theme-list" class="theme-popup" aria-label="Themes" role="menu">
                            <li role="none"><button role="menuitem" class="theme" id="light">Light (default)</button></li>
                            <li role="none"><button role="menuitem" class="theme" id="rust">Rust</button></li>
                            <li role="none"><button role="menuitem" class="theme" id="coal">Coal</button></li>
                            <li role="none"><button role="menuitem" class="theme" id="navy">Navy</button></li>
                            <li role="none"><button role="menuitem" class="theme" id="ayu">Ayu</button></li>
                        </ul>
                        <button id="search-toggle" class="icon-button" type="button" title="Search. (Shortkey: s)" aria-label="Toggle Searchbar" aria-expanded="false" aria-keyshortcuts="S" aria-controls="searchbar">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>

                    <h1 class="menu-title">CPython3.8 源码探秘</h1>

                    <div class="right-buttons">
                        <a href="print.html" title="Print this book" aria-label="Print this book">
                            <i id="print-button" class="fa fa-print"></i>
                        </a>
                        <a href="https://github.com/satori1995/cpython-internal" title="Git repository" aria-label="Git repository">
                            <i id="git-repository-button" class="fa fa-github"></i>
                        </a>
                    </div>
                </div>

                <div id="search-wrapper" class="hidden">
                    <form id="searchbar-outer" class="searchbar-outer">
                        <input type="search" id="searchbar" name="searchbar" placeholder="Search this book ..." aria-controls="searchresults-outer" aria-describedby="searchresults-header">
                    </form>
                    <div id="searchresults-outer" class="searchresults-outer hidden">
                        <div id="searchresults-header" class="searchresults-header"></div>
                        <ul id="searchresults">
                        </ul>
                    </div>
                </div>
                <!-- Apply ARIA attributes after the sidebar and the sidebar toggle button are added to the DOM -->
                <script type="text/javascript">
                    document.getElementById('sidebar-toggle').setAttribute('aria-expanded', sidebar === 'visible');
                    document.getElementById('sidebar').setAttribute('aria-hidden', sidebar !== 'visible');
                    Array.from(document.querySelectorAll('#sidebar a')).forEach(function(link) {
                        link.setAttribute('tabIndex', sidebar === 'visible' ? 0 : -1);
                    });
                </script>

                <div id="content" class="content">
                    <main>
                        <h2 id="楔子"><a class="header" href="#楔子">楔子</a></h2>
<p>上一篇文章我们介绍了 Python 的异常是怎么实现的，抛出异常这个动作在虚拟机层面上是怎样的一个行为，以及虚拟机在处理异常时的栈帧展开行为。</p>
<p>既然虚拟机内建的异常处理动作我们已经了解了，那么接下来就看看异常捕获是如何实现的，还有它又是如何影响虚拟机的异常处理流程的。毕竟在大部分情况下，我们都不会将异常抛出去，而是将它捕获起来。</p>
<h2 id="异常捕获语句"><a class="header" href="#异常捕获语句">异常捕获语句</a></h2>
<p>这里先来回顾一下异常捕获语句，首先一个完整的异常捕获语句如下。</p>
<pre><code class="language-python">try:
    pass
except IndexError as e:
    pass
except Exception as e:
    pass
else:
    pass
finally:
    pass 
</code></pre>
<p>情况可以分为以下几种：</p>
<p><font color="darkblue"><strong>1）如果 try 里面的代码在执行时没有出现异常，那么会执行 else ，然后执行 finally。</strong></font></p>
<pre><code class="language-python">try:
    print(&quot;我是 try&quot;)
except Exception as e:
    print(&quot;我是 except&quot;)
else:
    print(&quot;我是 else&quot;)
finally:
    print(&quot;我是 finally&quot;)
&quot;&quot;&quot;
我是 try
我是 else
我是 finally
&quot;&quot;&quot;    
</code></pre>
<p><font color="darkblue"><strong>2）如果 try 里面的代码在执行时出现异常了（异常会被设置在线程状态对象中），那么会依次判断 except（可以有多个）能否匹配发生的异常。如果某个 except 将异常捕获了，那么会将异常给清空，然后执行 finally。</strong></font></p>
<pre><code class="language-python">try:
    raise IndexError(&quot;IndexError Occurred&quot;)
except ValueError as e:
    print(&quot;ValueError 匹配上了异常&quot;)
except IndexError as e:
    print(&quot;IndexError 匹配上了异常&quot;)
except Exception as e:
    print(&quot;Exception 匹配上了异常&quot;)
else:
    print(&quot;我是 else&quot;)
finally:
    print(&quot;我是 finally&quot;)
&quot;&quot;&quot;
IndexError 匹配上了异常
我是 finally
&quot;&quot;&quot;   
</code></pre>
<p>except 子句可以有很多个，发生异常时会从上往下依次匹配。但是注意：多个 except 子句最多只有一个被执行，比如当前的 IndexError 和 Exception 都能匹配发生的异常，但只会执行匹配上的第一个 except 子句。</p>
<p>另外只要发生异常了，else 就不会执行了。不管 except 有没有将异常捕获到，都不会执行 else，因为 else 只有在 try 里面没有发生异常的时候才会执行。</p>
<p><font color="darkblue"><strong>3）如果 try 里面的代码在执行时出现异常了，但 except 没有将异常捕获掉，那么异常仍然被保存在线程状态对象中，然后执行 finally。如果 finally 子句中没有出现 return、break、continue 等关键字，再将异常抛出来。</strong></font></p>
<pre><code class="language-python">try:
    raise IndexError(&quot;IndexError Occurred&quot;)
except ValueError:
    print(&quot;ValueError 匹配上了异常&quot;)
finally:
    print(&quot;我是 finally&quot;)
&quot;&quot;&quot;
我是 finally
Traceback (most recent call last):
  File &quot;......&quot;, line 2, in &lt;module&gt;
    raise IndexError(&quot;IndexError Occurred&quot;)
IndexError: IndexError Occurred
&quot;&quot;&quot;
</code></pre>
<p>except 没有将异常捕获掉，所以执行完 finally 之后，异常又被抛出来了。但如果 finally 里面出现了 return、break、continue 等关键字，也不会抛出异常，而是将异常丢弃掉。</p>
<pre><code class="language-python">def f():
    try:
        raise IndexError(&quot;IndexError Occurred&quot;)
    except ValueError:
        print(&quot;ValueError 匹配上了异常&quot;)
    finally:
        print(&quot;我是 finally&quot;)
        return

f()
&quot;&quot;&quot;
我是 finally
&quot;&quot;&quot;

def g():
    for i in range(3):
        try:
            raise IndexError(&quot;IndexError Occurred&quot;)
        except ValueError:
            print(&quot;ValueError 匹配上了异常&quot;)
        finally:
            print(f&quot;我是 finally，i = {i}&quot;)
            continue

g()
&quot;&quot;&quot;
我是 finally，i = 0
我是 finally，i = 1
我是 finally，i = 2
&quot;&quot;&quot;
</code></pre>
<p>由于 finally 里面出现了 return 和 continue，所以异常并没有发生，而是被丢弃掉了。这个特性相信有很多小伙伴之前还是没有发现的。</p>
<p>然后 try、except、else、finally 这几个关键字不需要同时出现，可以有以下几种组合。</p>
<pre><code class="language-python">try ... except

try ... finally

try ... except ... else

try ... except ... else ... finally
</code></pre>
<p>注意里面的 except，可以出现多次，但其它关键字在一个 try 语句内只能出现一次。</p>
<h2 id="返回值问题"><a class="header" href="#返回值问题">返回值问题</a></h2>
<p>如果这几个关键字对应的代码块都指定了返回值，那么听谁的呢？下面解释一下。</p>
<pre><code class="language-python">def retval():
    try:
        return 123
    except Exception:
        return 456

print(retval())  # 123
</code></pre>
<p>由于没有发生异常，所以返回了 try 指定的返回值。</p>
<pre><code class="language-python">def retval():
    try:
        return 123
    except Exception:
        return 456
    else:
        return 789

print(retval())  # 123
</code></pre>
<p>虽然指定了 else，但是 try 里面已经执行 return 了，所以打印的仍是 try 的返回值。</p>
<pre><code class="language-python">def retval():
    try:
        1 / 0
        return 123
    except Exception:
        return 456

print(retval())  # 456
</code></pre>
<p>由于发生异常，所以返回了 except 指定的返回值。</p>
<pre><code class="language-python">def retval():
    try:
        1 / 0
        return 123
    except Exception:
        return 456
    else:
        return 789

print(retval())  # 456
</code></pre>
<p>一旦发生异常，else 就不可能执行，所以此时仍然返回 456。</p>
<pre><code class="language-python">def retval():
    try:
        return 123
    except Exception:
        return 456
    finally:
        pass

print(retval())  # 123
</code></pre>
<p>finally 永远会执行，但它没有指定返回值，所以此时返回的是 123。</p>
<pre><code class="language-python">def retval():
    try:
        return 123
    except Exception:
        return 456
    finally:
        return

print(retval())  # None
</code></pre>
<p>一旦 finally 中出现了 return，那么返回的都是 finally 指定的返回值。并且此时即便出现了没有捕获的异常，也不会报错，因为会将异常丢弃掉。</p>
<pre><code class="language-python">def retval():
    try:
        return 123
    except Exception:
        return 456
    finally:
        pass
    return 789

print(retval())  # 123
</code></pre>
<p>函数一旦 return，就表示要返回了，但如果这个 return 是位于出现了 finally 的异常捕获语句中，那么会先执行 finally，然后再返回。所以最后的 return 789 是不会执行的，因为已经出现 return 了，finally 执行完毕之后就直接返回了。</p>
<pre><code class="language-python">def retval():
    try:
        pass
    except Exception:
        return 456
    finally:
        pass
    return 789

print(retval())  # 789
</code></pre>
<p>没有异常，所以 except 里的 return 不会执行，而 try 和 finally 里面也没有 return，因此返回 789。</p>
<blockquote>
<p>一个简单的异常捕获，总结起来还稍微有点绕呢。</p>
</blockquote>
<p>从 Python 的层面理解完异常捕获之后，再来看看虚拟机是如何实现这一机制的？想要搞清楚这一点，还是得从字节码入手。</p>
<h2 id="异常捕获对应的字节码"><a class="header" href="#异常捕获对应的字节码">异常捕获对应的字节码</a></h2>
<p>随便写一段代码，然后反编译一下。</p>
<pre><code class="language-python">import dis

code_string = &quot;&quot;&quot;
try:
    raise Exception(&quot;抛出一个异常&quot;)
except Exception as e:
    print(e)
finally:
    print(&quot;我一定会被执行的&quot;)
&quot;&quot;&quot;

dis.dis(compile(code_string, &quot;exception&quot;, &quot;exec&quot;))
</code></pre>
<p>抛异常有两种方式，一种是虚拟机执行的时候出现错误而抛出异常，另一种是使用 raise 关键字手动抛出异常。这里我们就用第二种方式，来看一下反编译的结果（为了清晰，省略掉了源代码行号）。</p>
<pre><code class="language-C">      0 SETUP_FINALLY           60 (to 62)
      2 SETUP_FINALLY           12 (to 16)

      4 LOAD_NAME                1 (Exception)
      6 LOAD_CONST               1 ('抛出一个异常')
      8 CALL_FUNCTION            1
     10 RAISE_VARARGS            1
     12 POP_BLOCK
     14 JUMP_FORWARD            42 (to 58)

&gt;&gt;   16 DUP_TOP
     18 LOAD_NAME                1 (Exception)
     20 COMPARE_OP              10 (exception match)
     22 POP_JUMP_IF_FALSE       56
     24 POP_TOP
     26 STORE_NAME               2 (e)
     28 POP_TOP
     30 SETUP_FINALLY           12 (to 44)

     32 LOAD_NAME                0 (print)
     34 LOAD_NAME                2 (e)
     36 CALL_FUNCTION            1
     38 POP_TOP
     40 POP_BLOCK
     42 BEGIN_FINALLY
&gt;&gt;   44 LOAD_CONST               2 (None)
     46 STORE_NAME               2 (e)
     48 DELETE_NAME              2 (e)
     50 END_FINALLY
     52 POP_EXCEPT
     54 JUMP_FORWARD             2 (to 58)
&gt;&gt;   56 END_FINALLY
&gt;&gt;   58 POP_BLOCK
     60 BEGIN_FINALLY

&gt;&gt;   62 LOAD_NAME                0 (print)
     64 LOAD_CONST               0 ('我一定会被执行的')
     66 CALL_FUNCTION            1
     68 POP_TOP
     70 END_FINALLY
     72 LOAD_CONST               2 (None)
     74 RETURN_VALUE
</code></pre>
<p>指令集还是有点复杂的，因为要分好几种情况。</p>
<ul>
<li>try 里面没有出现异常。</li>
<li>try 里面出现了异常，但是 except 没有捕获到。</li>
<li>try 里面出现了异常，except 捕获到了。</li>
</ul>
<p>但我们知道无论是哪种情况，都要执行 finally，所以开头有两个 SETUP_FINALLY 指令，但为什么会有两个呢？因为在 Python 的异常处理机制中，<font color="blue">try-except-finally</font> 结构会被编译成两个嵌套的异常处理块：</p>
<ul>
<li>第一个 SETUP_FINALLY 是为了处理 finally 块，会把 finally 块的地址压入栈中，它确保无论 try 块中是否发生异常，finally 块中的代码都会被执行；</li>
<li>第二个 SETUP_FINALLY 实际上是在处理 except 块，在 Python 的字节码层面，except 块也是通过 SETUP_FINALLY 实现的；</li>
</ul>
<p>我们来看一下 SETUP_FINALLY 指令都干了什么。</p>
<pre><code class="language-C">case TARGET(SETUP_FINALLY): {
    PyFrame_BlockSetup(f, SETUP_FINALLY, INSTR_OFFSET() + oparg,
                       STACK_LEVEL());
    DISPATCH();
}
</code></pre>
<p>该指令内部仅仅是调用了 PyFrame_BlockSetup 函数，但是参数我们需要解释一下。</p>
<ul>
<li>f：当前的栈帧对象。</li>
<li>SETUP_FINALLY：指令本身，一个整数，值为 122。</li>
<li>INSTR_OFFSET()：一个宏，下一条待执行指令的偏移量，如果再加上 oparg，那么会对应 finally 子句（或 except 子句）。</li>
<li>STACK_LEVEL()：返回运行时栈的元素个数。</li>
</ul>
<p>下面看看 PyFrame_BlockSetup 函数的本体。</p>
<pre><code class="language-C">// Objects/frameobject.c

void
PyFrame_BlockSetup(PyFrameObject *f, int type, int handler, int level)
{
    // 关于 PyTryBlock 我们稍后再聊，总之 except 和 finally 都会对应 SETUP_FINALLY 指令
    // 虚拟机都会为它们创建 PyTryBlock
    PyTryBlock *b;
    // 一会儿解释
    if (f-&gt;f_iblock &gt;= CO_MAXBLOCKS)
        Py_FatalError(&quot;XXX block stack overflow&quot;);
    // 栈帧有一个 f_blockstack 字段，它是 PyTryBlock 类型的数组
    // 当栈帧创建完毕后，f_blockstack 的内存就已经申请好了
    // 因此当需要创建 PyTryBlock 实例时，只需从 f_blockstack 里面获取即可
    b = &amp;f-&gt;f_blockstack[f-&gt;f_iblock++];
    // 设置 PyTryBlock 实例的字段，这个结构体一会儿说
    b-&gt;b_type = type;
    b-&gt;b_level = level;
    b-&gt;b_handler = handler;
}
</code></pre>
<p>当解释器发现 except 和 finally 时，在进入 try 语句块之前会先执行 SETUP_FINALLY 指令，通过索引 f_iblock 从 f_blockstack 数组中获取 PyTryBlock。</p>
<ul>
<li>每获取一个 PyTryBlock，f_iblock 会自增 1；</li>
<li>当 except 或 finally 执行完毕时，要交还对应的 PyTryBlock，所以 f_iblock 会自减 1。</li>
</ul>
<p>然后注意一下上面代码中的 if 条件，CO_MAXBLOCKS 是一个宏，值为 20，所以 f_iblock 的值必须小于 20。这也意味着，try 语句不能嵌套太深。我们举例说明：</p>
<p><img src="./images/205.png" alt="" /></p>
<p>每个 try 都对应一个 except，因为屏幕不够，这里只截取了一半。每次进入 try 之前，会提前执行 SETUP_FINALLY，获取 PyTryBlock。由于每获取一个，f_iblock 自增 1，而这里嵌套了 20 层，导致 f_iblock 达到了 20，所以报错了，这是一个在编译阶段就能检测出的错误。</p>
<p>如果我们去掉一层呢？看看报不报错。</p>
<p><img src="./images/206.png" alt="" /></p>
<p>结果没有问题，当然啦，如果不是恶意代码，我个人认为不会存在嵌套层级如此之深的异常捕获。</p>
<p>然后再来看看里面的 f_iblock，它表示对应的 PyTryBlock 在 f_blockstack 数组中的索引。栈帧刚创建时，f_iblock 的值为 0，每当执行 SETUP_FINALLY 指令时，就会从 f_blockstack 数组中获取一个 PyTryBlock，然后 f_iblock 自增 1。那么 PyTryBlock 长什么样子呢？</p>
<pre><code class="language-C">// Include/frameobject.h
typedef struct {
    int b_type;
    int b_handler;
    int b_level;
} PyTryBlock;
</code></pre>
<p>b_type 表示 block 的种类，因为存在多种用途的 PyTryBlock 对象，除了 SETUP_FINALLY 之外还有 SETUP_WITH 等。然后在 PyFrame_BlockSetup 中我们看到它被设置成了参数 type，而参数 type 接收的就是当前虚拟机正在执行的字节码指令。因此 PyTryBlock 具有多种用途，具体用于哪种则基于字节码指令进行判断。</p>
<p>b_handler 表示处理程序的字节码偏移量，即跳转目标，比如当前的 try 语句块，当 try 执行完了或者执行出错后，要跳转到什么位置呢？在 SETUP_FINALLY 指令中我们看到它被设置成了 <font color="blue">INSTR_OFFSET() + oparg</font>，所以它会跳转到 finally 或 except 所在的位置。</p>
<p>b_level 表示进入 try 语句块时的 STACK_LEVEL()，即运行时栈的深度，或者说当前运行时栈的元素个数，因为当发生异常时，要把运行时栈恢复到进入 try 语句块时的状态。</p>
<pre><code class="language-python"># 假设此时运行时栈的深度是 n
try:                          # SETUP_FINALLY 执行时 b_level = n
    ...                       # 执行内部逻辑
    raise Exception(&quot;error&quot;)  # 在这里不幸发生异常，那么要将栈恢复到 b_level 记录的深度 n
except Exception:
    pass
</code></pre>
<p>所以 b_level 相当于一个检查点，通过 b_level，可以在发生异常时将运行时栈恢复到进入 try 时的状态。这种检查点机制确保了异常处理的可靠性，因为无论 try 块中发生什么，我们总能回到一个已知的、正确的栈状态。</p>
<p>然后我们再回头看开头的两个指令：</p>
<pre><code class="language-C">      0 SETUP_FINALLY           60 (to 62)
      2 SETUP_FINALLY           12 (to 16)
</code></pre>
<p>执行之后，f_blockstack 数组的布局如下：</p>
<p><img src="./images/207.png" alt="" /></p>
<p>取出两块 PyTryBlock，第一块对应 finally，会无条件执行，第二块对应 except，异常捕获的时候用。至于具体怎么做的稍后再说，我们先回到抛异常的地方看看。</p>
<pre><code class="language-C">      // 加载 &lt;class 'Exception'&gt;
      4 LOAD_NAME                1 (Exception)
      // 加载字符串
      6 LOAD_CONST               1 ('抛出一个异常')
      // 尽管 Exception 是一个类，但调用的指令也同样是 CALL_FUNCTION
      // 至于这个指令的具体细节后面会介绍
      // 这里只需要知道一个异常对象已经被创建出来了，并被压入了运行时栈
      8 CALL_FUNCTION            1
      // 从运行时栈中弹出异常对象，然后抛出
     10 RAISE_VARARGS            1
</code></pre>
<p>下面我们来看一下 RAISE_VARARGS 指令。</p>
<pre><code class="language-C">case TARGET(RAISE_VARARGS): {
    PyObject *cause = NULL, *exc = NULL;
    // raise 一个异常有三种方式
    // 1）重新抛出当前异常，只写一个 raise 即可，此时 oparg = 0
    // 2）抛出指定异常：raise exc，此时 oparg = 1
    // 3）抛出指定异常并指定原因：raise exc from cause，此时 oparg = 2
    // 所以当前的 oparg = 1
    switch (oparg) {
    case 2:
        cause = POP(); /* cause */
        /* fall through */
    case 1:
        exc = POP(); /* exc */
        /* fall through */
    case 0:
        // 调用 do_raise 函数，将异常设置在线程状态对象中
        if (do_raise(tstate, exc, cause)) {
            goto exception_unwind;
        }
        break;
    default:
        _PyErr_SetString(tstate, PyExc_SystemError,
                         &quot;bad RAISE_VARARGS oparg&quot;);
        break;
    }
    goto error;
}
</code></pre>
<p>当异常设置完毕后，我们看到它跳转到了帧评估函数的 exception_unwind 标签，执行异常捕获。</p>
<pre><code class="language-C">exception_unwind:
    // 虚拟机在进入 try 代码块之前，会为 except 和 finally 块创建 PyTryBlock
    // 对于当前来说，由于同时指定了 except 和 finally，因此会存在两个 PyTryBlock
    // 所以 f-&gt;f_iblock 的值为 2
    while (f-&gt;f_iblock &gt; 0) {
        // 弹出 PyTryBlock，因为 except 在后面，所以要从后往前获取
        PyTryBlock *b = &amp;f-&gt;f_blockstack[--f-&gt;f_iblock];
        
        // EXCEPT_HANDLER 定义在 opcode.h 中，值为 257，用于异常处理
        // 但比较特殊的是，它不是一个指令，至于相关细节后续会看到
        if (b-&gt;b_type == EXCEPT_HANDLER) {  // 如果两者相等的话
            // 这是一个宏，所做的事情如下
            // 从线程状态对象中拿到 exc_info，这个和 python 里的 sys.exc_info() 等价
            // 然后从栈顶弹出 exc_type、exc_value、exc_traceback，并设置在 exc_info 中
            UNWIND_EXCEPT_HANDLER(b);
            continue;
        }
        // UNWIND_BLOCK 是一个宏，所做的事情如下
        /*
            // 如果当前栈深度大于进入 try 块时记录的深度
            // 不断从栈顶弹出对象，并减少引用计数
            #define UNWIND_BLOCK(b) \
                while (STACK_LEVEL() &gt; (b)-&gt;b_level) { \
                    PyObject *v = POP(); \
                    Py_XDECREF(v); \
                }
        */
        // 这个 b_level 我们上面说过的，它保存了进入 try 块时的运行时栈的深度
        // 因此这个宏就是用来倒掉多余的栈内容，把栈恢复到之前保存的检查点状态
        UNWIND_BLOCK(b);
        // 对于当前的代码而言，第一次弹出的 PyTryBlock 用于 except
        // 它的 b_type = SETUP_FINALLY，b_handler = 16
        if (b-&gt;b_type == SETUP_FINALLY) {
            // 异常类型、异常值、回溯栈
            PyObject *exc, *val, *tb;
            // 拿到 b_handler，一会要跳转的目标位置，也就是 except 所在位置
            int handler = b-&gt;b_handler;
            // 从线程状态对象中拿到 exc_info，这个 exc_info 保存的还是旧异常的 exc_info
            // 然后 exc_info 有三个字段，假设抛出的异常是 ValueError(&quot;值错了&quot;)
            // exc_info-&gt;exc_type 就是 &lt;class 'ValueError'&gt;
            // exc_info-&gt;exc_value 就是抛出的异常对象本身
            // exc_info-&gt;exc_traceback 就是回溯栈
            // exc_info-&gt;previous_item 指向上一个 _PyErr_StackItem 实例
            _PyErr_StackItem *exc_info = tstate-&gt;exc_info;
            // 将当前 PyTryBlock 的 b_type 设置为 EXCEPT_HANDLER
            PyFrame_BlockSetup(f, EXCEPT_HANDLER, -1, STACK_LEVEL());
            // 将旧异常的 exc_type、exc_value、exc_traceback 压入运行时栈
            PUSH(exc_info-&gt;exc_traceback);
            PUSH(exc_info-&gt;exc_value);
            if (exc_info-&gt;exc_type != NULL) {
                PUSH(exc_info-&gt;exc_type);
            }
            else {
                Py_INCREF(Py_None);
                PUSH(Py_None);
            }
            // 在 RAISE_VARARGS 指令中调用了 do_raise，设置了新异常
            // 这里是拿到新异常的 exc_type、exc_value、exc_traceback
            _PyErr_Fetch(tstate, &amp;exc, &amp;val, &amp;tb);
            // 对异常规范化处理，不用关注
            _PyErr_NormalizeException(tstate, &amp;exc, &amp;val, &amp;tb);
            if (tb != NULL)
                PyException_SetTraceback(val, tb);
            else
                PyException_SetTraceback(val, Py_None);
            // 用新异常的 exc_type、exc_value、exc_traceback 更新 exc_info
            Py_INCREF(exc);
            exc_info-&gt;exc_type = exc;
            Py_INCREF(val);
            exc_info-&gt;exc_value = val;
            exc_info-&gt;exc_traceback = tb;
            if (tb == NULL)
                tb = Py_None;
            Py_INCREF(tb);
            // 将新异常的 exc_type、exc_value、exc_traceback 也压入运行时栈
            PUSH(tb);
            PUSH(val);
            PUSH(exc);
            // 绝对跳转，跳转到偏移量为 handler 的指令
            JUMPTO(handler);
            /* Resume normal execution */
            goto main_loop;
        }
    } /* unwind stack */

    /* End the loop as we still have an error */
    break;
} /* main loop */

assert(retval == NULL);
assert(_PyErr_Occurred(tstate));
</code></pre>
<p>我们看到虚拟机调用 PUSH 将旧异常和新异常的 exc_traceback、exc_value、exc_type 分别压入运行时栈中，并且知道此时开发者已经为异常处理做好了准备，所以接下来的异常处理工作，则需要交给开发者指定的代码来解决。于是内部调用了 <code>JUMPTO(b-&gt;b_handler)</code>，将虚拟机要执行的下一条指令设置为异常处理代码编译后所得到的第一条字节码指令。</p>
<p>因为第一个弹出的 PyTryBlock 的 b_handler 为 16，那么虚拟机将要执行的下一条指令就是偏移量为 16 的指令，而这条指令就是 DUP_TOP。</p>
<pre><code class="language-C">     // 在上面的 exception_unwind 标签中调用了 6 个 PUSH
     // 按照从栈顶到栈底顺序，目前运行时栈的元素如下
     /* 新异常的 exc_type
      * 新异常的 exc_value
      * 新异常的 exc_traceback
      * 旧异常的 exc_type
      * 旧异常的 exc_value
      * 旧异常的 exc_traceback
      */
     // DUP_TOP 指令之前介绍过，它会将栈顶元素拷贝一份，然后重新压入运行时栈
     // 显然这里就是新异常的 exc_type，即 &lt;class 'Exception'&gt;
&gt;&gt;   16 DUP_TOP
     // 因为是 except Excepion as e，所以将 &lt;class 'Exception'&gt; 压入运行时栈
     18 LOAD_NAME                1 (Exception)
     // 将前两个元素从运行时栈中弹出，分别是 except 后面指定的异常类型、新异常的 exc_type
     // 然后比较产生的异常的类型是否是 except 指定的异常类型的子类
     20 COMPARE_OP              10 (exception match)
     // 因为 raise 了一个 Exception 对象，所以 exc_type 就是 Exception
     // 而 except 子句后面指定的也是 Exception，所以是匹配的
     // 如果不匹配，那么跳转到偏移量为 56 的指令，去执行 finally
     22 POP_JUMP_IF_FALSE       56
     // 这个指令内部负责弹出栈顶元素，减少引用计数，直接丢弃
     // 目前栈里面有 6 个元素，栈顶元素是新异常的 exc_type
     // 所以 POP_TOP 之后，栈顶元素就变成了新异常的 exc_value
     24 POP_TOP
     // 弹出栈顶的 exc_value，赋值给变量 e，到此 except Exception as e 完成
     // 我们看到这个过程其实也是一个变量赋值，字节码为 STORE_NAME
     26 STORE_NAME               2 (e)
     // 继续弹出栈顶元素，此时是新异常的 exc_traceback
     28 POP_TOP
     // 这里为啥又出现一个 SETUP_FINALLY 指令？很简单
     /*
      try:
          pass
      except Exception as e:
          pass
      
      上面这段代码，在内部会变成下面这样
      
      try:
          pass
      except Exception as e:
          try:
              pass
          finally:
              del e
      */
     // 所以这里会多出一个 SETUP_FINALLY，因为内部又嵌套了一个 try ... finally
     // 至于这么做的原因，我们稍后解释
     30 SETUP_FINALLY           12 (to 44)
     // 以下四条指令对应 except 子句内的 print(e)
     32 LOAD_NAME                0 (print)
     34 LOAD_NAME                2 (e)
     36 CALL_FUNCTION            1
     38 POP_TOP
     // except 子句里的代码执行完毕，调用 POP_BLOCK
     // 该指令内部会交还 PyTryBlock，然后 f_iblock--
     // 注意：这一步交还的 PyTryBlock，是 except 内部的 finally 对应的 PyTryBlock
     40 POP_BLOCK
     // BEGIN_FINALLY 会往栈顶 PUSH 一个 NULL 进去，标识 finally 的开始
     // 注意：这个 finally 是 except 子句内部的 finally，是解释器自动生成的
     42 BEGIN_FINALLY
     // 将 e 赋值为 None，然后将 e 删除掉
&gt;&gt;   44 LOAD_CONST               2 (None)
     46 STORE_NAME               2 (e)
     48 DELETE_NAME              2 (e)
     50 END_FINALLY
     // 到此整个 except 执行完毕，然后执行 POP_EXCEPT，交还对应的 PyTryBlock
     // 然后在该指令内部还会恢复之前保存的异常状态，我们上面看到，解释器往运行时栈里面推了 6 个元素
     // 前 3 个已经被弹出了，还剩下旧异常的 exc_type、exc_value、exc_traceback
     // 那么将它们继续弹出，赋值给 exc_info 里面的字段，相当于恢复成之前的异常状态
     52 POP_EXCEPT
     // 跳转到第 58 条指令
     54 JUMP_FORWARD             2 (to 58)    
</code></pre>
<p>上面的内容有点多，我们再单独解释一下，首先在 exception_unwind 标签内部获取 <code>tstate-&gt;exc_info</code> 的三个字段，它们是旧异常的 exc_type、exc_value、exc_traceback，然后压入运行时栈。再通过 _PyErr_Fetch 获取 tstate 里面的新异常的 exc_type、exc_value、exc_traceback，用它们更新 <code>tstate-&gt;exc_info</code>，然后再压入运行时栈。</p>
<p>所以此时运行时栈里面有 6 个元素。</p>
<p><img src="./images/208.png" alt="" /></p>
<p>然后使用 JUMPTO 跳转到偏移量为 <code>b-&gt;b_handler</code> 的指令，对于当前来说就是 except 子句对应的指令，然后执行。</p>
<ul>
<li>通过 DUP_TOP 将栈顶元素拷贝一份并入栈。</li>
<li>通过 LOAD_NAME 将 except 子句指定的异常类型入栈。</li>
<li>通过 COMPARE_OP 将栈顶的两个元素弹出，进行比较，将比较结果入栈。</li>
<li>再通过 POP_JUMP_IF_FALSE 将比较结果弹出，进行判断，由于新异常的 exc_type 和 except 子句指定的异常类型都是 Exception，所以结果为 True。</li>
</ul>
<p>我们画张图，展示一下运行时栈的变化过程。</p>
<p><img src="./images/209.png" alt="" /></p>
<p>然后是 30 SETUP_FINALLY，至于为什么会多出这条指令，原因我们也解释了。</p>
<pre><code class="language-Python">e = 2.71

try:
    raise Exception(&quot;Some Error&quot;)
except Exception as e:
    # 一些逻辑
    ...

print(e)
&quot;&quot;&quot;
NameError: name 'e' is not defined
&quot;&quot;&quot;
# 打印 print(e) 的时候居然 NameError 了
# 因为上面的代码会被转成下面这个样子
try:
    raise Exception(&quot;Some Error&quot;)
except Exception as e:
    try:
        # 一些逻辑
        ...
    finally:
        del e
</code></pre>
<p>所以又产生了一个 SETUP_FINALLY 指令，至于解释器这么做的动机我们稍后解释。</p>
<p>然后偏移量为 32、34、36、38 的指令就无需解释了，这几条指令执行完毕后，except 语句块里的代码就执行完了。然后执行 40 POP_BLOCK，它会交还当前 except 内部的 finally 语句块对应的 PyTryBlock，然后将 f_iblock 自减 1。</p>
<pre><code class="language-C">case TARGET(POP_BLOCK): {
    PREDICTED(POP_BLOCK);
    PyFrame_BlockPop(f);
    DISPATCH();
}

// Objects/frameobject.c
PyTryBlock *
PyFrame_BlockPop(PyFrameObject *f)
{
    PyTryBlock *b;
    if (f-&gt;f_iblock &lt;= 0)
        Py_FatalError(&quot;XXX block stack underflow&quot;);
    b = &amp;f-&gt;f_blockstack[--f-&gt;f_iblock];
    return b;
}
</code></pre>
<p>接着将变量 e 赋值为 None，然后删除变量 e，完事之后再执行 52 POP_EXCEPT。</p>
<pre><code class="language-C">case TARGET(POP_EXCEPT): {
    PyObject *type, *value, *traceback;
    _PyErr_StackItem *exc_info;
    // 同样调用 PyFrame_BlockPop，拿到 except 对应的 PyTryBlock
    PyTryBlock *b = PyFrame_BlockPop(f);
    // 在 exception_unwind 标签中，将 b_type 设置成了 EXCEPT_HANDLER
    // 所以这里一定等于 EXCEPT_HANDLER，否则不应该执行 POP_EXCEPT 指令
    if (b-&gt;b_type != EXCEPT_HANDLER) {
        _PyErr_SetString(tstate, PyExc_SystemError,
                         &quot;popped block is not an except handler&quot;);
        goto error;
    }
    assert(STACK_LEVEL() &gt;= (b)-&gt;b_level + 3 &amp;&amp;
           STACK_LEVEL() &lt;= (b)-&gt;b_level + 4);
    // 此时 exc_info 里面保存的是新异常的 exc_info、exc_type、exc_value
    // 但是新异常被捕获了
    exc_info = tstate-&gt;exc_info;
    type = exc_info-&gt;exc_type;
    value = exc_info-&gt;exc_value;
    traceback = exc_info-&gt;exc_traceback;
    // 那么应该将 exc_info 的字段改成之前的旧异常的 exc_info、exc_type、exc_value
    exc_info-&gt;exc_type = POP();
    exc_info-&gt;exc_value = POP();
    exc_info-&gt;exc_traceback = POP();
    // 减少引用计数
    Py_XDECREF(type);
    Py_XDECREF(value);
    Py_XDECREF(traceback);
    DISPATCH();
}
</code></pre>
<p>到此整个 except 语句块我们就分析完了，接下来是 finally 语句块。</p>
<pre><code class="language-C">     // 交还 finally 语句块对应的 PyTryBlock，将 f_iblock 自减 1
&gt;&gt;   58 POP_BLOCK
     // finally 语句块的开始
     60 BEGIN_FINALLY
     // 内部的代码逻辑
&gt;&gt;   62 LOAD_NAME                0 (print)
     64 LOAD_CONST               0 ('我一定会被执行的')
     66 CALL_FUNCTION            1
     68 POP_TOP
     // 如果异常未被捕获掉，那么向上传播，让外层的异常处理程序去处理它
     70 END_FINALLY
     72 LOAD_CONST               2 (None)
     74 RETURN_VALUE
</code></pre>
<p>因此在异常机制的实现中，最重要的就是线程状态以及栈帧对象的 f_blockstack 字段里面存放的 PyTryBlock 对象。首先根据线程状态可以判断当前是否发生了异常，而 PyTryBlock 对象则告诉虚拟机，开发者是否为异常设置了 except 和 finally，虚拟机异常处理的流程就是在线程所处的状态和 PyTryBlock 的共同作用下完成的。</p>
<p>当然啦，我们这里分析的是异常能捕获的情况，如果不能捕获呢？具体细节可以自己写段代码测试一下，这里我们直接画张图总结一下。</p>
<p><img src="./images/210.png" alt="" /></p>
<p>另外这张图只适用于一个 except 子句的情况，如果有多个 except 子句，那么当第一个不匹配时，应该要顺序匹配下一个。</p>
<p>总之 Python 中一旦出现异常了，那么会将异常类型、异常值、异常回溯栈设置在线程状态对象中，然后栈帧一步一步地回退，寻找异常捕获代码（从内向外）。如果退到了模块级别还没有发现异常捕获，那么从外向内打印 traceback 中的信息，当走到最内层的时候再将线程中设置的异常类型和异常值打印出来。</p>
<pre><code class="language-Python">def h():
    1 / 0

def g():
    h()

def f():
    g()

f()

# traceback 回溯栈
Traceback (most recent call last):
  # 打印模块的 traceback
  # 并提示：发生错误是因为在第 10 行调用了 f()
  File &quot;/Users/.../main.py&quot;, line 10, in &lt;module&gt;
    f()

  # 打印函数 f 的 traceback
  # 并提示：发生错误是因为在第 8 行调用了 g()
  File &quot;/Users/.../main.py&quot;, line 8, in f
    g()

  # 打印函数 g 的 traceback
  # 并提示：发生错误是因为在第 5 行调用了 h()
  File &quot;/Users/.../main.py&quot;, line 5, in g
    h()

  # 打印函数 h 的 traceback
  # 并提示：发生错误是因为在第 2 行执行了 1 / 0
  File &quot;/Users/.../main.py&quot;, line 2, in h
    1 / 0

# 函数 h 的 traceback-&gt;tb_next 为 None，证明错误是发生在函数 h 中
# 而在模块中调用函数 f 相当于导火索，然后一层一层输出，最终定位到函数 h
# 最后再将之前设置在线程状态对象中的异常类型和异常值打印出来即可
ZeroDivisionError: division by zero
</code></pre>
<p>模块中调用了函数 f，函数 f 调用了函数 g，函数 g 调用了函数 h。然后在函数 h 中执行出错了，但又没有异常捕获，那么会将执行权交给函数 g 对应的栈帧，但是函数 g 也没有异常捕获，那么再将执行权交给函数 f 对应的栈帧。所以调用的时候，栈帧一层层创建，当执行完毕或者出现异常时，栈帧再一层层回退。</p>
<p><img src="./images/211.png" alt="" /></p>
<p>因此栈帧的遍历顺序是<font color="blue">从函数 h 到模块</font>，traceback 的遍历顺序是<font color="blue">从模块到函数 h</font>。</p>
<h2 id="为什么要执行-del"><a class="header" href="#为什么要执行-del">为什么要执行 del</a></h2>
<p>前面说了，在 except 语句块内，如果将异常赋给了某个变量，那么 except 结束时会将变量删掉。</p>
<pre><code class="language-python">e = 2.71

def get_e():
    return e

try:
    raise Exception(&quot;我要引发异常了&quot;)
except Exception as e:
    # 因为 except Exception as e 位于全局作用域
    # 所以执行完之后，全局变量 e 就被修改了
    print(get_e())  # 我要引发异常了
    # 但是在最后还会隐式地执行 del e，那为什么要这么做呢？
    # 因为 except 子句结束后，变量 e 指向的异常对象就没用了
    # 而如果不 del e 的话，那么异常对象不会被销毁
    # 此外还有一个原因，通过 __traceback__ 可以拿到当前的回溯栈，即 traceback 对象
    print(e.__traceback__)  # &lt;traceback object at 0x104a98b80&gt;
    # 而 traceback 对象保存了当前的栈帧，然后栈帧又保存了包含变量 e 的名字空间
    print(e.__traceback__.tb_frame.f_locals[&quot;e&quot;] is e)  # True
    # 相信你能猜到这会带来什么后果，没错，就是循环引用
    # 因此在 except 结束时会隐式地 del e

# 显然当 except 结束后，全局变量 e 就无法访问了
print(e)
&quot;&quot;&quot;
NameError: name 'e' is not defined
&quot;&quot;&quot;
</code></pre>
<p>所以在附加了回溯信息的情况下，它们会形成堆栈帧的循环引用，在下一次垃圾回收执行之前，会使所有变量都保持存活。</p>
<h2 id="小结"><a class="header" href="#小结">小结</a></h2>
<p>本篇文章我们就分析了异常捕获的实现原理，总的来说并不难。另外在更高的版本中，所有的信息会静态保存在一张异常跳转表中，速度会更快。当然啦，在没有报错时，异常捕获对程序性能没有任何影响，所以放心使用。</p>
<hr />
<p> </p>
<p><strong>欢迎大家关注我的公众号：古明地觉的编程教室。</strong></p>
<p><img src="./images/qrcode_for_gh.jpg" alt="" /></p>
<p><strong>如果觉得文章对你有所帮助，也可以请作者吃个馒头，Thanks♪(･ω･)ﾉ。</strong></p>
<p><img src="./images/supports.png" alt="" /></p>

                    </main>

                    <nav class="nav-wrapper" aria-label="Page navigation">
                        <!-- Mobile navigation buttons -->
                            <a rel="prev" href="63.异常是怎么实现的？虚拟机是如何将异常抛出去的？.html" class="mobile-nav-chapters previous" title="Previous chapter" aria-label="Previous chapter" aria-keyshortcuts="Left">
                                <i class="fa fa-angle-left"></i>
                            </a>
                            <a rel="next" href="65.函数在底层长什么样子？.html" class="mobile-nav-chapters next" title="Next chapter" aria-label="Next chapter" aria-keyshortcuts="Right">
                                <i class="fa fa-angle-right"></i>
                            </a>
                        <div style="clear: both"></div>
                    </nav>
                </div>
            </div>

            <nav class="nav-wide-wrapper" aria-label="Page navigation">
                    <a rel="prev" href="63.异常是怎么实现的？虚拟机是如何将异常抛出去的？.html" class="nav-chapters previous" title="Previous chapter" aria-label="Previous chapter" aria-keyshortcuts="Left">
                        <i class="fa fa-angle-left"></i>
                    </a>
                    <a rel="next" href="65.函数在底层长什么样子？.html" class="nav-chapters next" title="Next chapter" aria-label="Next chapter" aria-keyshortcuts="Right">
                        <i class="fa fa-angle-right"></i>
                    </a>
            </nav>

        </div>

        <script type="text/javascript">
            window.playground_copyable = true;
        </script>
        <script src="elasticlunr.min.js" type="text/javascript" charset="utf-8"></script>
        <script src="mark.min.js" type="text/javascript" charset="utf-8"></script>
        <script src="searcher.js" type="text/javascript" charset="utf-8"></script>
        <script src="clipboard.min.js" type="text/javascript" charset="utf-8"></script>
        <script src="highlight.js" type="text/javascript" charset="utf-8"></script>
        <script src="book.js" type="text/javascript" charset="utf-8"></script>

        <!-- Custom JS scripts -->
        <script type="text/javascript" src="theme/custom.js"></script>
    </body>
</html>
